### ISSUE TITLE
test simd failure

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/complexespp#22]
```
/home/max/code/complexespp/complexes++/test/unit-test/test_simd_energy.cpp:113: Failure
Value of: v2.at(idx)
  Actual: -4
Expected: v1.at(idx)
Which is: 4
```

@berenger-eu  can you have a look? You might be faster on those.

**Comment by berenger-eu** [comment]
@kain88-de it is fixed, no?

**Comment by kain88-de** [comment]
No is still an issue. I just commented out the test right now to get notified by the test pipeline to know if we break something in the C++ code.

**Comment by berenger-eu** [comment]
On my computer and the repo is not commented:
https://github.com/bio-phys/complexespp/blob/main/complexes%2B%2B/test/unit-test/test_simd_energy.cpp#L113
and it seems to pass, or maybe I missed something?

**Comment by kain88-de** [comment]
yes it is: https://github.com/bio-phys/complexespp/blob/main/complexes%2B%2B/test/unit-test/test_simd_energy.cpp#L125

You only found the macro definition. I commented out the usage
